name: eslint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      
      # Check out the repository 
      - uses: actions/checkout@v2
 
      # Install Node.js 
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.1
 
      # Install your dependencies 
      - run: npx eslint . --ext .js,.jsx,.ts,.tsx
